### ISSUE TITLE
Sway support

### ISSUE THREAD

**Issue by travankor** [KJoke70/i3-tools#2]
Would you be interested in adding support for the [Sway](https://swaywm.org/) Wayland Compositor to your repo?

i3ipc-python has support for sway, but some stuff needs to be tweaked. I made rotate_layout.py work, and can take a look at the other files if you are interested.

**Comment by KJoke70** [comment]
I'm generally interested as long as all scripts remain compatible to i3. If you want to suggest code-changes or submit PRs, feel free to do so! Just be warned that it might take me a couple days before I get to it.
